//! Time as **filtration** (SPEC §F11): how an agent's information field grows
//! along the runs of a system.
//!
//! The static field core ([`crate::observational_field`]) answers "what can an
//! agent distinguish about a single state?". This module adds *time*. The sample
//! space `Ω` is the set of finite runs (traces) of the trace LTS; a **filtration**
//! is a non-decreasing sequence of information fields `F_0 ⊆ F_1 ⊆ … ⊆ F_T` over
//! `Ω`, where `F_t` is generated by the observations the agent has made over the
//! first `t` states a run visits. Non-decreasing means *finer over time*: later fields
//! refine earlier ones. This is **memory** — a refusal to coarsen — the discrete
//! analogue of the σ-algebra filtration of a stochastic process (§F11), with the
//! probability layer deliberately omitted (§F10).
//!
//! Concretely, the agent watches the presence coordinates (§F3) of each state a
//! run visits, producing an *observation sequence*. Two runs sit in the same atom
//! of `F_t` iff their observation sequences agree on the first `t` visited states
//! — the agent cannot yet tell the runs apart from `t` steps of watching.
//!
//! ```
//! use stratum_core::term::{input, lift, quote, zero, par};
//! use stratum_lts::Lts;
//! use stratum_field::filtration::{filtration, is_filtration};
//!
//! // a⟨|0|⟩ | a(y).x⟨|0|⟩ observed on x: the barb on x appears after one step.
//! let x = quote(zero());
//! let a = quote(lift(quote(zero()), zero()));
//! let sys = par([lift(a.clone(), zero()), input(a, move |_| lift(x.clone(), zero()))]);
//! let lts = Lts::explore(&sys, 100);
//! let fields = filtration(&lts, &[quote(zero())], 3);
//! assert_eq!(fields[0].num_atoms(), 1); // F_0 knows nothing
//! assert!(is_filtration(&fields));       // information only grows
//! ```

use std::collections::BTreeSet;

use stratum_core::Name;
use stratum_lts::Lts;

use crate::{project, Field};

/// A finite **run** of the LTS (an outcome in the sample space `Ω`, §F11).
///
/// It records the sequence of visited state indices (`states`, always beginning
/// at the initial state) together with the `≡N`-canonical channel labels *and*
/// transmitted messages of the `Comm` steps taken between them. The two event
/// vectors run in lock-step, so step `i` is the `(channel, message)` pair
/// `(labels[i], messages[i])`, and
/// `labels.len() == messages.len() == states.len() - 1`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Trace {
    /// The visited state indices, in order, starting at [`Lts::initial`].
    pub states: Vec<usize>,
    /// The firing-channel labels of the steps taken, one per transition.
    pub labels: Vec<Name>,
    /// The transmitted messages (reified names `⌜Q⌝`) of the steps taken, one per
    /// transition and parallel to [`labels`](Trace::labels): step `i` is the
    /// `(channel, message)` event `(labels[i], messages[i])`.
    pub messages: Vec<Name>,
}

impl Trace {
    /// The number of steps (transitions) taken in this run.
    pub fn len(&self) -> usize {
        self.labels.len()
    }

    /// Whether the run took no steps (it consists of the initial state alone).
    pub fn is_empty(&self) -> bool {
        self.labels.is_empty()
    }
}

/// Enumerate all maximal runs from the initial state, each extended until it
/// reaches a terminal state or has taken `max_len` steps (§F11).
///
/// Exploration is depth-first following the LTS transition order, so the result
/// is deterministic. A run *stops early* at a terminal state (a deadlock / normal
/// form): its trace is shorter than `max_len` but is still a complete outcome of
/// `Ω`. When `max_len` is `0`, the sole run is the initial state alone.
///
/// Note: only per-run *length* is bounded (by `max_len`); the *number* of runs
/// can grow exponentially with branching, so keep `max_len` modest on wide LTSs.
pub fn enumerate_traces(lts: &Lts, max_len: usize) -> Vec<Trace> {
    let mut out = Vec::new();
    let mut states = vec![lts.initial()];
    let mut labels: Vec<Name> = Vec::new();
    let mut messages: Vec<Name> = Vec::new();
    dfs(lts, max_len, &mut states, &mut labels, &mut messages, &mut out);
    out
}

/// Depth-first helper for [`enumerate_traces`]: records a trace at every leaf
/// (terminal state or `max_len` steps reached) and recurses otherwise.
fn dfs(
    lts: &Lts,
    max_len: usize,
    states: &mut Vec<usize>,
    labels: &mut Vec<Name>,
    messages: &mut Vec<Name>,
    out: &mut Vec<Trace>,
) {
    let cur = *states.last().expect("trace always has a current state");
    if labels.len() == max_len || lts.is_terminal(cur) {
        out.push(Trace {
            states: states.clone(),
            labels: labels.clone(),
            messages: messages.clone(),
        });
        return;
    }
    for t in lts.transitions(cur) {
        states.push(t.target);
        labels.push(t.label.clone());
        messages.push(t.message.clone());
        dfs(lts, max_len, states, labels, messages, out);
        messages.pop();
        labels.pop();
        states.pop();
    }
}

/// The agent's observation sequence for a run: its presence projection (§F3) of
/// each visited state, in order.
fn observation_sequence(lts: &Lts, trace: &Trace, observed: &[Name]) -> Vec<BTreeSet<Name>> {
    trace
        .states
        .iter()
        .map(|&i| project(lts.state(i), observed))
        .collect()
}

/// Build the filtration `F_0 ⊆ F_1 ⊆ … ⊆ F_T` that an agent observing `observed`
/// generates along the runs of `lts` (§F11). `T` is the number of states the
/// longest run visits — a run of `L` steps contributes `L + 1` observations, so
/// the finest field `F_T` separates runs that diverge only at the horizon.
///
/// The sample space `Ω` is [`enumerate_traces`]`(lts, max_len)`. Each returned
/// [`Field`] partitions `Ω`: two runs share an atom of `F_t` iff their
/// observation sequences (their presence projection of each visited state, §F3)
/// agree on the first `t` visited states — i.e. the agent, having watched `t`
/// steps, cannot yet separate them. `F_0` is generated by the empty prefix, so it
/// is the trivial field (one atom): before observing anything the agent knows
/// nothing. Each `F_t` reuses [`Field::from_signatures`] with the length-`t`
/// observation prefix as the signature.
///
/// The sequence is non-decreasing in information (see [`is_filtration`]): the
/// length-`(t+1)` prefix determines the length-`t` prefix, so `F_{t+1}` always
/// refines `F_t`.
pub fn filtration(lts: &Lts, observed: &[Name], max_len: usize) -> Vec<Field> {
    let traces = enumerate_traces(lts, max_len);
    let sequences: Vec<Vec<BTreeSet<Name>>> = traces
        .iter()
        .map(|tr| observation_sequence(lts, tr, observed))
        .collect();

    // The horizon is the longest observation sequence: a run of `L` steps visits
    // `L + 1` states, so to separate runs that only diverge at the last visited
    // state the finest field must reveal up to `max run length + 1` observations
    // (indexing by `max_len` alone would drop the horizon state of full-budget
    // runs).
    let horizon = sequences.iter().map(Vec::len).max().unwrap_or(0);

    (0..=horizon)
        .map(|t| {
            let signatures: Vec<Vec<BTreeSet<Name>>> = sequences
                .iter()
                .map(|seq| seq.iter().take(t).cloned().collect())
                .collect();
            Field::from_signatures(&signatures)
        })
        .collect()
}

/// Verify that `fields` is a filtration (§F11): each `F_{t+1}` refines `F_t`, so
/// information is non-decreasing over time (memory = refusal to coarsen).
///
/// A slice of length `0` or `1` is vacuously a filtration.
pub fn is_filtration(fields: &[Field]) -> bool {
    fields.windows(2).all(|w| w[1].refines(&w[0]))
}
