//! # stratum-field
//!
//! The **field grain** (σ) of the πρσϕ-Formalism: information fields over the
//! ρ-calculus configuration space, following the PI-SIGFPT informational-fields
//! substrate. See `SPEC.md` §F for the modelling decisions.
//!
//! On the bounded trace LTS the configuration space is finite, so a finite
//! σ-algebra is exactly a **partition** ([`Field`]); its blocks are the field's
//! **atoms** (its resolution limit). An [`Agent`] is a pair of channel sets
//! `(obs, ctl)` — what it can watch and what it can drive; its information field
//! is the pullback σ-algebra of the **projection** onto its observed channels
//! ([`Agent::field`]). The [`is_measurable`] check is the honesty constraint:
//! an action is legible for an agent iff it is constant on the atoms the agent
//! cannot separate.
//!
//! ```
//! use stratum_field::Field;
//! // The discrete field (full knowledge) refines every field; the trivial
//! // field (no knowledge) is refined by every field.
//! let discrete = Field::discrete(3);
//! let trivial = Field::trivial(3);
//! assert!(discrete.refines(&trivial));
//! assert!(!trivial.refines(&discrete));
//! ```

pub mod content;
pub mod filtration;

use std::collections::HashMap;
use std::collections::BTreeSet;
use std::hash::Hash;

use stratum_core::{canonicalize_name, name_equiv, Name, Proc};
use stratum_lts::Lts;

/// An information field over an `n`-state configuration space: a finite
/// σ-algebra, represented by its atoms as a partition.
///
/// Block ids are normalized (assigned in order of first appearance), so two
/// `Field`s are equal exactly when they induce the same partition.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Field {
    block_of: Vec<usize>,
    num_atoms: usize,
}

impl Field {
    /// Build a field from a per-state signature: two states share an atom iff
    /// their signatures are equal. This is the field *generated by* the
    /// observations the signatures encode.
    pub fn from_signatures<S: Eq + Hash + Clone>(signatures: &[S]) -> Field {
        let mut ids: HashMap<S, usize> = HashMap::new();
        let mut block_of = Vec::with_capacity(signatures.len());
        for s in signatures {
            let next = ids.len();
            let id = *ids.entry(s.clone()).or_insert(next);
            block_of.push(id);
        }
        Field {
            num_atoms: ids.len(),
            block_of,
        }
    }

    /// The discrete field: every state is its own atom (omniscience).
    pub fn discrete(n: usize) -> Field {
        Field {
            block_of: (0..n).collect(),
            num_atoms: n,
        }
    }

    /// The trivial field: one atom containing all states (no knowledge).
    pub fn trivial(n: usize) -> Field {
        Field {
            block_of: vec![0; n],
            num_atoms: usize::from(n > 0),
        }
    }

    /// The number of states this field is defined over.
    pub fn len(&self) -> usize {
        self.block_of.len()
    }

    /// Whether the configuration space is empty.
    pub fn is_empty(&self) -> bool {
        self.block_of.is_empty()
    }

    /// The number of atoms (blocks).
    pub fn num_atoms(&self) -> usize {
        self.num_atoms
    }

    /// The atom (block id) containing state `i`.
    pub fn atom_of(&self, i: usize) -> usize {
        self.block_of[i]
    }

    /// The atoms as lists of state indices.
    pub fn atoms(&self) -> Vec<Vec<usize>> {
        let mut out = vec![Vec::new(); self.num_atoms];
        for (i, &b) in self.block_of.iter().enumerate() {
            out[b].push(i);
        }
        out
    }

    /// Whether `self` is finer than or equal to `other`: every atom of `self`
    /// sits inside an atom of `other` (`self` can tell apart at least as much).
    pub fn refines(&self, other: &Field) -> bool {
        debug_assert_eq!(self.len(), other.len());
        let mut map: HashMap<usize, usize> = HashMap::new();
        for i in 0..self.len() {
            let (s, o) = (self.block_of[i], other.block_of[i]);
            match map.get(&s) {
                Some(&o2) if o2 != o => return false,
                Some(_) => {}
                None => {
                    map.insert(s, o);
                }
            }
        }
        true
    }

    /// Pooled knowledge: the common refinement (two states share an atom iff
    /// indistinguishable to *both*). Finer than either input.
    pub fn pooled(&self, other: &Field) -> Field {
        debug_assert_eq!(self.len(), other.len());
        let sigs: Vec<(usize, usize)> = (0..self.len())
            .map(|i| (self.block_of[i], other.block_of[i]))
            .collect();
        Field::from_signatures(&sigs)
    }

    /// Common knowledge: the transitive closure of the union of the two
    /// indistinguishabilities (coarser than either input).
    pub fn common_knowledge(&self, other: &Field) -> Field {
        debug_assert_eq!(self.len(), other.len());
        let n = self.len();
        let mut uf = UnionFind::new(n);
        merge_within(&mut uf, &self.block_of);
        merge_within(&mut uf, &other.block_of);
        let roots: Vec<usize> = (0..n).map(|i| uf.find(i)).collect();
        Field::from_signatures(&roots)
    }
}

/// Merge all states that share a block, according to `block_of`.
fn merge_within(uf: &mut UnionFind, block_of: &[usize]) {
    let mut first: HashMap<usize, usize> = HashMap::new();
    for (i, &b) in block_of.iter().enumerate() {
        match first.get(&b) {
            Some(&rep) => uf.union(i, rep),
            None => {
                first.insert(b, i);
            }
        }
    }
}

struct UnionFind {
    parent: Vec<usize>,
}

impl UnionFind {
    fn new(n: usize) -> UnionFind {
        UnionFind {
            parent: (0..n).collect(),
        }
    }
    fn find(&mut self, x: usize) -> usize {
        let mut r = x;
        while self.parent[r] != r {
            r = self.parent[r];
        }
        // Path compression.
        let mut c = x;
        while self.parent[c] != r {
            let next = self.parent[c];
            self.parent[c] = r;
            c = next;
        }
        r
    }
    fn union(&mut self, a: usize, b: usize) {
        let (ra, rb) = (self.find(a), self.find(b));
        if ra != rb {
            self.parent[ra] = rb;
        }
    }
}

/// An agent: the channels it can observe and the channels it can drive (§F5).
#[derive(Clone, Debug)]
pub struct Agent {
    /// Channels this agent can watch — determines its information field.
    pub obs: Vec<Name>,
    /// Channels this agent can output on — its space of actions.
    pub ctl: Vec<Name>,
}

impl Agent {
    /// An observer (no control capability).
    pub fn observer(obs: Vec<Name>) -> Agent {
        Agent { obs, ctl: Vec::new() }
    }

    /// This agent's information field over the LTS: the pullback σ-algebra of its
    /// projection (§F6).
    pub fn field(&self, lts: &Lts) -> Field {
        observational_field(lts, &self.obs)
    }
}

/// Active parallel components of a (canonical) process.
fn components(p: &Proc) -> Vec<&Proc> {
    match p {
        Proc::Zero => Vec::new(),
        Proc::Par(ps) => ps.iter().collect(),
        other => vec![other],
    }
}

/// The projection `π` of a state onto observed channels (§F6): the set of
/// observed channels on which the state currently has an output (presence
/// coordinates, §F3). Names are returned canonically.
pub fn project(state: &Proc, obs: &[Name]) -> BTreeSet<Name> {
    let comps = components(state);
    obs.iter()
        .filter(|c| {
            comps.iter().any(|k| match k {
                Proc::Lift { chan, .. } => name_equiv(chan, c),
                _ => false,
            })
        })
        .map(canonicalize_name)
        .collect()
}

/// The field over the LTS induced by observing `obs`: states are in the same
/// atom iff their projections agree.
pub fn observational_field(lts: &Lts, obs: &[Name]) -> Field {
    let sigs: Vec<BTreeSet<Name>> = (0..lts.num_states())
        .map(|i| project(lts.state(i), obs))
        .collect();
    Field::from_signatures(&sigs)
}

/// Whether an action (given as one value per state) is **measurable** w.r.t.
/// `field`: constant on every atom (§F8). Equivalently, `field` refines the
/// action's own generated field ([`generated_field`]).
pub fn is_measurable<V: Eq>(field: &Field, values: &[V]) -> bool {
    debug_assert_eq!(field.len(), values.len());
    let mut rep: HashMap<usize, &V> = HashMap::new();
    for (i, v) in values.iter().enumerate() {
        match rep.get(&field.block_of[i]) {
            Some(&w) if w != v => return false,
            Some(_) => {}
            None => {
                rep.insert(field.block_of[i], v);
            }
        }
    }
    true
}

/// The coarsest field w.r.t. which the given action is measurable: the partition
/// by action value.
pub fn generated_field<V: Eq + Hash + Clone>(values: &[V]) -> Field {
    Field::from_signatures(values)
}
